services:
  - type: web
    name: blaze-studio
    runtime: node
    region: oregon
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
